# version: "3.7"

# services:
#   nginx-proxy:
#     image: jwilder/nginx-proxy
#     container_name: nginx-proxy
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - ./certs:/etc/nginx/certs
#       - ./vhost:/etc/nginx/vhost.d
#       - ./html:/usr/share/nginx/html
#     labels:
#       - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
#     restart: always
#   nginx-proxy-acme:
#     image: nginxproxy/acme-companion
#     container_name: nginx-proxy-acme
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - ./certs:/etc/nginx/certs
#       - ./vhost:/etc/nginx/vhost.d
#       - ./html:/usr/share/nginx/html
#       - ./acme:/etc/acme.sh
#     environment:
#       - DEFAULT_EMAIL=shubham.garg@mail.utoronto.ca
#   frontend:
#     image: ghcr.io/utsc-cscc09-programming-on-the-web/frontend-taggit:latest
#     container_name: frontend
#     restart: always
#     expose:
#       - 80
#     environment:
#       - VIRTUAL_HOST=taggit.tech
#       - LETSENCRYPT_HOST=taggit.tech
#     env_file:
#       - ./frontend/.env.local
#   backend:
#     image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-taggit:latest
#     container_name: backend
#     restart: always
#     expose:
#       - 4242
#     environment:
#       - VIRTUAL_HOST=api.taggit.tech
#       - LETSENCRYPT_HOST=api.taggit.tech
#     env_file:
#       - ./backend/.env

version: '3.8'

services:
  frontend:
    image: ghcr.io/your-org/your-frontend-image:latest
    container_name: frontend
    expose:
      - "80"
    restart: always

  backend:
    image: ghcr.io/your-org/your-backend-image:latest
    container_name: backend
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest  # official image
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    restart: always
