version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=shubham.garg@mail.utoronto.ca
  frontend:
    image: ghcr.io/uoft-utsc-cs-sandbox/frontend-taggit
    container_name: frontend
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=taggit.tech
      - LETSENCRYPT_HOST=taggit.tech
    env_file:
      - ./frontend/.env.local
  backend:
    image: ghcr.io/uoft-utsc-cs-sandbox/backend-taggit
    container_name: backend
    restart: always
    expose:
      - 4242
    environment:
      - VIRTUAL_HOST=api.taggit.tech
      - LETSENCRYPT_HOST=api.taggit.tech
    env_file:
      - ./backend/.env