version: '3.8'

services:
  frontend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/frontend-taggit
    container_name: frontend
    env_file: ./frontend/.env.local
    expose:
      - "3000"
    restart: always

  backend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-taggit
    container_name: backend
    env_file: ./backend/.env
    expose:
      - "4242"
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: