version: '3.8'

services:
  frontend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/frontend-taggit
    container_name: frontend
    env_file: ./frontend/.env.local
    expose:
      - "3000"
    restart: always
  peerjs:
    image: peerjs/peerjs-server:latest
    container_name: peerjs
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - DEBUG=peerjs:*
    restart: always
  backend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-taggit
    container_name: backend
    env_file: ./backend/.env
    ports:
      - "4242:4242"
    depends_on:
      - postgres
    restart: always

  nginx:
    image: staticfloat/nginx-certbot
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./nginx/certbot:/etc/letsencrypt
    environment:
      - CERTBOT_EMAIL=shubham.garg@mail.utoronto.ca
      - CERTBOT_DOMAINS=taggit.tech,api.taggit.tech
      - CERTBOT_EXTRA_ARGS=--agree-tos
    depends_on:
      - frontend
      - backend
      - peerjs
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: