version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: dbtaggit
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  frontend:
    image: ghcr.io/your-org/your-frontend-image:latest
    container_name: frontend
    expose:
      - "80"
    restart: always

  backend:
    image: ghcr.io/your-org/your-backend-image:latest
    container_name: backend
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest  # official image
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data: